#!/bin/sh
# Render lumo-tamer's config.yaml from environment variables, restore the token
# vault, then hand off to the CLI.
#
# lumo-tamer reads process.env exactly once (for $HOME) — every other setting
# comes from config.yaml. Railway only offers environment variables, so this
# script is the bridge between the two.

set -eu

SESSIONS_DIR="${LUMO_SESSIONS_DIR:-/app/sessions}"
SECRETS_DIR="${LUMO_SECRETS_DIR:-/app/secrets}"
VAULT_PATH="$SESSIONS_DIR/vault.enc"
VAULT_KEY_PATH="$SECRETS_DIR/lumo-vault-key"
CONFIG_PATH="${LUMO_CONFIG_PATH:-/app/config.yaml}"

die() {
  echo "lumo-tamer entrypoint: $1" >&2
  exit 1
}

# Fail fast on values lumo-tamer's zod schema would reject. It exits on a bad
# config, so without this a typo in a Railway variable reads as a crash loop.
require_oneof() {
  name="$1"; value="$2"; shift 2
  for allowed in "$@"; do
    [ "$value" = "$allowed" ] && return 0
  done
  die "$name=$value is not valid — allowed: $*"
}

# YAML single-quoted scalar: the only escape inside one is a doubled quote, so
# any key or path is safe to interpolate once it has been through this.
yaml_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"
}

mkdir -p "$SESSIONS_DIR" "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

# ---------------------------------------------------------------------------
# Vault key
# ---------------------------------------------------------------------------
# No OS keychain exists in a container, so the AES key for the token vault comes
# from a file. Generate it once with `openssl rand -base64 32` and keep it in
# sync with whatever machine created the vault — a mismatched key reads as
# "wrong key or corrupted file".
if [ -n "${LUMO_VAULT_KEY:-}" ]; then
  printf '%s' "$LUMO_VAULT_KEY" > "$VAULT_KEY_PATH"
  chmod 600 "$VAULT_KEY_PATH"
elif [ ! -f "$VAULT_KEY_PATH" ]; then
  die "LUMO_VAULT_KEY is not set and no key file exists at $VAULT_KEY_PATH.
Generate one locally with: openssl rand -base64 32"
fi

# ---------------------------------------------------------------------------
# Vault seeding
# ---------------------------------------------------------------------------
# Seed only when the volume has no vault yet. Overwriting on every boot would
# roll the tokens back to the ones captured at authentication time, and Proton
# rotates the refresh token on every refresh — the stale one is already dead.
if [ -n "${LUMO_VAULT_SEED:-}" ] && [ ! -f "$VAULT_PATH" ]; then
  echo "lumo-tamer entrypoint: seeding token vault from LUMO_VAULT_SEED" >&2
  printf '%s' "$LUMO_VAULT_SEED" | base64 -d > "$VAULT_PATH" \
    || die "LUMO_VAULT_SEED is not valid base64"
  chmod 600 "$VAULT_PATH"
fi

if [ ! -f "$VAULT_PATH" ] && [ "${1:-server}" = "server" ]; then
  echo "lumo-tamer entrypoint: no token vault at $VAULT_PATH." >&2
  echo "Authenticate locally and set LUMO_VAULT_SEED, or run 'tamer auth login'" >&2
  echo "inside this container (railway ssh) before starting the server." >&2
fi

# ---------------------------------------------------------------------------
# config.yaml
# ---------------------------------------------------------------------------
# Rendered fresh on every boot: the volume holds tokens, not configuration, so
# changing a Railway variable is all it takes to change behaviour.
[ -n "${LUMO_API_KEY:-}" ] || die "LUMO_API_KEY is not set — it is the only thing guarding this deployment"

# Railway injects PORT. lumo-tamer binds whatever config.yaml says, so the two
# have to agree or the healthcheck (and every request) hits a closed port.
PORT="${PORT:-3003}"

require_oneof LUMO_AUTH_METHOD "${LUMO_AUTH_METHOD:-login}" login browser rclone
require_oneof LUMO_DEFAULT_MODEL_TIER "${LUMO_DEFAULT_MODEL_TIER:-auto}" auto lumo-lite lumo-max
require_oneof LUMO_REASONING_DEFAULT "${LUMO_REASONING_DEFAULT:-none}" none high
require_oneof LUMO_LOG_LEVEL "${LUMO_LOG_LEVEL:-info}" trace debug info warn error fatal

cat > "$CONFIG_PATH" <<YAML
# Generated by entrypoint.sh on container start. Edits here are lost on restart;
# change the Railway variables instead.
auth:
  method: $(yaml_quote "${LUMO_AUTH_METHOD:-login}")
  vault:
    path: $(yaml_quote "$VAULT_PATH")
    keyFilePath: $(yaml_quote "$VAULT_KEY_PATH")
  autoRefresh:
    enabled: true
    intervalHours: ${LUMO_REFRESH_INTERVAL_HOURS:-20}
    onError: true

log:
  level: $(yaml_quote "${LUMO_LOG_LEVEL:-info}")
  target: 'stdout'
  messageContent: ${LUMO_LOG_MESSAGE_CONTENT:-false}

conversations:
  databasePath: $(yaml_quote "$SESSIONS_DIR/")

server:
  port: ${PORT}
  apiKey: $(yaml_quote "$LUMO_API_KEY")
  defaultModelTier: $(yaml_quote "${LUMO_DEFAULT_MODEL_TIER:-auto}")
  bodyLimit: $(yaml_quote "${LUMO_BODY_LIMIT:-360kb}")
  reasoning:
    default: $(yaml_quote "${LUMO_REASONING_DEFAULT:-none}")
    surfaceThinking: ${LUMO_SURFACE_THINKING:-false}
  enableWebSearch: ${LUMO_ENABLE_WEB_SEARCH:-false}
  customTools:
    # Lumo has no native tool calling — lumo-tamer emulates it by describing the
    # tools in the prompt and parsing JSON back out. Cipher's email pipeline
    # sends no tools and does not need this; the chat agent does nothing without
    # it. Enabling it lets model output trigger client-side actions, which is
    # why upstream ships it off.
    enabled: ${LUMO_CUSTOM_TOOLS:-false}
  metrics:
    enabled: ${LUMO_METRICS:-false}
YAML

echo "lumo-tamer entrypoint: config rendered, starting on port ${PORT}" >&2

case "${1:-server}" in
  server) shift 2>/dev/null || true; exec tamer server "$@" ;;
  auth)   shift; exec tamer auth "$@" ;;
  cli)    shift; exec tamer "$@" ;;
  *)      exec "$@" ;;
esac
