name: Atlas Runner

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [self-hosted, unraid]
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello from Unraid!"
