name: Atlas Runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, unraid]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up docker compose
        run: docker compose version

      - name: Stop existing containers
        run: docker compose -f ./backend/docker-compose.yml down

      - name: Build and start container
        run: docker compose -f ./backend/docker-compose.yml up -d
