name: Atlas Runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, unraid]
    steps:
      - name: Start build
        run: echo "Starting build step!!!!!"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print Info
        run: |
          echo "Hostname: $(hostname)"
          echo "Running as: $(whoami)"
          echo "Current directory: ${pwd}"
          echo "Files:"
          ls -la
          echo "OS Info:"
          uname -a

      - name: Stop existing containers
        run: docker compose -f ./backend/docker-compose.yml down

      - name: Build and start container
        run: docker compose -f ./backend/docker-compose.yml up --build -d
