name: Atlas Runner

on:
  push:
    branches:
      - master

jobs:
  checkout_repo:
    runs-on: [self-hosted, unraid]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print Info
        run: |
          echo "Hostname: $(hostname)"
          echo "Running as: $(whoami)"
          echo "Current directory: ${pwd}"
          echo "Files:"
          ls -la
          echo "OS Info:"
          uname -a

  copy_env_files:
    runs-on: [self-hosted, unraid]
    needs: build
    steps:
      - name: Copy Env Files
        run: |
          cp /mnt/user/LoganShare/Code/secrets/pennywise/.env ./backend/go-gmail/.env
          cp /mnt/user/LoganShare/Code/secrets/pennywise/.env ./backend/go-pennywise-api/.env
          cp /mnt/user/LoganShare/Code/secrets/pennywise/pennywise-39654-c87f94721374.json ./backend/go-gmail/pennywise-39654-c87f94721374.json

  build_docker:
    runs-on: [self-hosted, unraid]
    needs: copy_env_files
    steps:
      - name: Stop existing container
        run: docker compose -f ./backend/docker-compose.yml down

      - name: Build and start containers
        run: docker compose -f ./backend/docker-compose.yml up --build -d
